remove into libc::statx_timestamp conversion for Timespec
Summary:
[#3978](https://github.com/rust-lang/libc/pull/3978) introduced the error bellow:
```
error[E0451]: field `__statx_timestamp_pad1` of struct `statx_timestamp` is private
  --> fbcode/hermetic_infra/reverie/reverie-syscalls/src/args/time.rs:56:13
   |
56 |             __statx_timestamp_pad1: [0],
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^ private field

error: aborting due to 1 previous error
```
Removing `From` impl since it does not appear to be used anywhere.

Reviewed By: zertosh

Differential Revision: D68680975

fbshipit-source-id: f54cb2e2cf1b6a03cda8b8427a7709a2793f2c67