Eliminate cast from &T to &mut T
Summary:
This code is 100% UB and no longer compiles in Rust 1.73.

```
error: casting `&T` to `&mut T` is undefined behavior, even if the reference is unused, consider instead using an `UnsafeCell`
   --> fbcode/hermetic_infra/reverie/experimental/reverie-sabre/src/thread.rs:652:32
    |
652 |             let slot_map_mut = &mut *((&*SLOT_MAP as *const _) as *mut _);
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[deny(invalid_reference_casting)]` on by default
```

Reviewed By: JakobDegen

Differential Revision: D50488164

fbshipit-source-id: ea649d97f47ccc329a44650aff5dc467ed12b48c